monolog:
  handlers:
    main:
      type: stream
      formatter: json_formatter
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: notice
      channels: [ "!event" ]

    errors:
      type: stream
      formatter: json_formatter
      path: "%kernel.logs_dir%/%kernel.environment%.error.log"
      level: error

